### ISSUE TITLE
change type of Amount to Int

### ISSUE THREAD

**Issue by epogrebnyak** [cmc-haskell-2018/seminars#1]
Может принять смелую гипотезу о том, что количество товара - это целое число? )
И к жизни ближе и для изучения типов разнообразнее.

https://github.com/cmc-haskell-2018/seminars/blob/f3909cfcaf351edc4ebf13365bd3fc9d96f218e8/seminar-03/Seminar_03.hs#L13-L14

**Comment by fizruk** [comment]
Данные материалы довольно устаревшие и просто находятся здесь для истории: у меня нет планов поддерживать их.

Но, отвечая на вопрос: количество товара далеко не всегда целое число (например, если товар на вес с ценой за килограмм, можно заказать 1.3 кг материала, например, или 2.7 метра ткани (если цена указана за метр)). Другое дело, что вместо чисел с плавающей точкой (`Double`) можно было бы использовать числа с фиксированной точкой (из `Data.Fixed`).

**Comment by epogrebnyak** [comment]
Килограммы, конечно, дробные, но тогда `Amount` не такое уж однозначное слово, может быть `Weight`. Сила же типизации в том чтобы приблизить классы типов к реальным явлениям - там где пачками или упаковками - `Amount`, где в граммах - `Weight`.  Немного режет, но конечно, не глобальный вопрос.

В любом случае спасибо, что вывесили материалы!
